theme: jekyll-theme-time-machine
title: Welcome to ScoJoh's homepage!
description: This will soon be a place for information about me and my professional self. And projects and such and that sort of thing!
